### ISSUE TITLE
Consider configuring some form of environment variable expiration monitor via GitHub Actions

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-api#2085]
Claude has a recommended way of doing so below, though I've done no verification, and this integrates with some outside technologies we don't use. More broadly, I wonder if it's really possible to create essentially a cronjob using GitHub Actions, as well as how easy it would be to alert to Slack.

------------------------------------------------------------------------------------------------

# GitHub PAT Expiration Monitoring

### 1. GitHub Actions Workflow

```yaml
name: PAT Expiration Monitor
on:
  schedule:
    - cron: '0 9 * * *'  # Run daily at 9am UTC
  workflow_dispatch:      # Allow manual triggers

env:
  PAT_CREATION_DATE: '2024-01-03'
  PAT_EXPIRY_DAYS: 90

jobs:
  check-pat-expiration:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate days until expiration
        id: calc-expiry
        run: |
          creation=$(date -d "$PAT_CREATION_DATE" +%s)
          expiry=$(date -d "$PAT_CREATION_DATE + $PAT_EXPIRY_DAYS days" +%s)
          today=$(date +%s)
          days_left=$(( ($expiry - $today) / 86400 ))
          echo "DAYS_LEFT=$days_left" >> $GITHUB_ENV
          
      - name: Check expiration thresholds
        run: |
          if [ $DAYS_LEFT -le 14 ]; then
            echo "::warning::PAT expires in $DAYS_LEFT days"
          fi
          if [ $DAYS_LEFT -le 3 ]; then
            echo "::error::PAT expiration critical: $DAYS_LEFT days remaining"
          fi

      - name: Send Slack notification (14 days)
        if: env.DAYS_LEFT <= 14
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'github-alerts'
          slack-message: ":warning: GitHub PAT expires in ${{ env.DAYS_LEFT }} days. Please schedule rotation."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send PagerDuty alert (3 days)
        if: env.DAYS_LEFT <= 3
        uses: PagerDuty/action@v3
        with:
          token: ${{ secrets.PAGERDUTY_TOKEN }}
          event-type: 'trigger'
          payload: |
            {
              "routing_key": "${{ secrets.PAGERDUTY_ROUTING_KEY }}",
              "event_action": "trigger",
              "payload": {
                "summary": "GitHub PAT Critical: Expires in ${{ env.DAYS_LEFT }} days",
                "severity": "critical",
                "source": "github-actions"
              }
            }

      - name: Create GitHub Issue (7 days)
        if: env.DAYS_LEFT <= 7
        uses: actions/github-script@v6
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 GitHub PAT expires in ${process.env.DAYS_LEFT} days`,
              body: `
              # PAT Expiration Alert
              
              - **Days Until Expiration**: ${process.env.DAYS_LEFT}
              - **Current PAT Creation Date**: ${process.env.PAT_CREATION_DATE}
              - **Expiration Date**: $(date -d "${process.env.PAT_CREATION_DATE} + ${process.env.PAT_EXPIRY_DAYS} days")
              
              ## Required Actions:
              1. Generate new PAT in GitHub
              2. Update PAT in GitHub Actions secrets
              3. Update PAT_CREATION_DATE in monitoring workflow
              4. Verify CI/CD pipelines with new token
              
              ## Security Checklist:
              - [ ] New PAT has correct scope permissions
              - [ ] Old PAT scheduled for deletion
              - [ ] Access audit performed
              - [ ] Dependent systems notified
              
              /cc @security-team @devops-team
              `
            });

### 2. Monitoring Dashboard Configuration

```yaml
# Grafana Dashboard Config
apiVersion: 1
panels:
  - title: "GitHub PAT Status"
    type: "gauge"
    datasource: "prometheus"
    targets:
      - expr: |
          (
            unix_timestamp(
              date_add(
                timestamp(github_pat_creation_date), interval 90 day
              )
            ) - unix_timestamp(now())
          ) / 86400
    thresholds:
      steps:
        - value: null
          color: "green"
          label: "OK"
        - value: 14
          color: "yellow"
          label: "Warning"
        - value: 7
          color: "orange"
          label: "Alert"
        - value: 3
          color: "red"
          label: "Critical"
    fieldConfig:
      defaults:
        unit: "days"
        min: 0
        max: 90
```

### 1. GitHub Secrets Required
```text
SLACK_BOT_TOKEN          # For Slack notifications
PAGERDUTY_TOKEN         # For PagerDuty alerts
PAGERDUTY_ROUTING_KEY   # For PagerDuty routing
```

### 2. Repository Configuration
```yaml
# .github/settings.yml
repository:
  # Ensure issues can be created by GitHub Actions
  has_issues: true
  # Configure branch protection to prevent accidental PAT commits
  branch_protection:
    main:
      required_status_checks:
        - "check-pat-expiration"
```

### 3. Prometheus Metrics
```yaml
# prometheus.yml
scrape_configs:
  - job_name: 'github-pat-monitor'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__name__]
        regex: 'github_pat_.*'
        action: keep
```

## Alert Escalation Path

1. **14 Days Before**:
   - Slack notification to `#github-alerts`
   - Warning status in Grafana dashboard
   - Email to security and DevOps teams

2. **7 Days Before**:
   - GitHub Issue created
   - Slack notification with @here mention
   - Orange alert status in Grafana
   - Daily reminder emails begin

3. **3 Days Before**:
   - PagerDuty incident created
   - Red alert status in Grafana
   - Slack notification to `#incident-response`
   - Management notification

4. **24 Hours Before**:
   - Hourly PagerDuty reminders
   - Incident bridge opened
   - Status page update
   - Executive team notification
```
