### ISSUE TITLE
Determine why standard API appears to have deployed with more than 1 instance consistently

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-api#2423]
Our GCP `app.yaml` configuration file for API v1 specifies a configuration of just one instance that runs perpetually. However, 2 months of logs from GCP imply that we had at least 2, and at most 8, instances running at times. I've attached a chart showing this phenomenon below. We should determine why, then deal with depending on cause.

![Image](https://github.com/user-attachments/assets/ac11f88f-3754-4902-9140-2a40f07b2425)

**Comment by mikesmit** [comment]
Taking a look. Theories to investigate so far.
1. We are launching and re-launching a lot causing one active but multiple non-active containers
2. Our container health check is failing causing Google to spin up more containers.

**Comment by mikesmit** [comment]
**we do only configure one instance** (at least in the latest version.

Current configuration of the latest version of the v1 service is the following which requires at least and no more than 1 instance.

```
runtime: custom
api_version: '1.0'
env: flexible
threadsafe: true
automatic_scaling:
  cool_down_period: 180s
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.8
resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 64
liveness_check:
  initial_delay_sec: '300'
  path: /liveness-check
  check_interval_sec: '30'
  timeout_sec: '30'
  failure_threshold: 5
  success_threshold: 2
readiness_check:
  path: /readiness-check
  check_interval_sec: '5'
  timeout_sec: '4'
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: '400'
service_account: github-deployment@policyengine-api.iam.gserviceaccount.com
flexible_runtime_settings:
  operating_system: ubuntu22
  runtime_version: '22'
```
